apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "prometheus-pvc"
  labels:
    name: "prometheus-volume"
spec:
  accessModes:
   - ReadWriteOnce
  resources:
     requests:
       storage: 1Gi
