apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: php
  template:
    metadata:
      name: php-pod
      labels:
        env: php
    spec:
      containers:
      - name: php-con
        image: vimal13/apache-webserver-php:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html"
            name: php-storage

      volumes:
      - name: php-storage
        persistentVolumeClaim:
          claimName: myphp-pv-claim
        

